[1] Fixed bug in GSV invocation that botched refresh logic. [2] Bumped release. [3] Added unit test target. [4] Added unrelated README notes. [5] All unit tests PASS. [6] Ublox 9 functional test WORKS.

diff --git a/Hazer/Makefile b/Hazer/Makefile
--- a/Hazer/Makefile
+++ b/Hazer/Makefile
@@ -22,7 +22,7 @@ TITLE				:=	Hazer
 
 MAJOR				:=	15# API changes that may require that applications be modified.
 MINOR				:=	3# Only functionality or features added with no legacy API changes.
-BUILD				:=	3# Only bugs fixed with no API changes or new functionality.
+BUILD				:=	4# Only bugs fixed with no API changes or new functionality.
 
 # Disclaimer: the only target that I routinely build and test for is "host", my
 # X86_64 Ubuntu build server.
@@ -699,3 +699,11 @@ install-include:
 	mkdir -p $(INSTALL_INC)
 	tar -C $(OUT)/$(INC_DIR) -cvf - . | tar -C $(INSTALL_INC) -xvf -
 	tar -C $(INC_DIR) -cvf - . | tar -C $(INSTALL_INC) -xvf -
+
+########## Unit test
+
+unit-test:
+	for U in $(TARGETUNITTESTS); do \
+		echo -n "UNIT TEST $$U "; \
+		test -f $$U && $$U && echo "PASS." || echo "FAIL!"; \
+	done
